services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SqlDatabase: Server=db,1433;Database=Barbearia;User Id=sa;Password=YourStrong@Password1;Encrypt=False;TrustServerCertificate=True
      Monitoring__HealthCheckKey: ${MONITORING__HEALTHCHECKKEY:-local-development-health-key}
      Serilog__MinimumLevel__Default: Information
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: barbearia-sql-server
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: YourStrong@Password1
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Password1 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
    driver: local
