name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore Barbearia.sln

      - name: Verify formatting
        run: dotnet format Barbearia.sln --verify-no-changes

      - name: Build
        run: dotnet build Barbearia.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Barbearia.sln --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Publish coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*
